import Head from 'next/head'

import Main from '@/components/common/Main'
import Header from '@/components/Header'
import EcoSection from '@/components/HomePage/EcoSection'
import PrizeSection from '@/components/HomePage/PrizeSection'
import RevolutionSection from '@/components/HomePage/RevolutionSection'
import StatsSection from '@/components/HomePage/StatsSection'
import TeamSection from '@/components/HomePage/TeamSection'
import TitleSection from '@/components/HomePage/TitleSection'
import SdkSection from '@/components/HomePage/SdkSection'
import RoadmapSection from '@/components/HomePage/RoadmapSection'
import PartnersSection from '@/components/HomePage/PartnersSection'
import StaySection from '@/components/HomePage/StaySection'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>DX - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main>
        <TitleSection />
        <RevolutionSection />
        <EcoSection />
        <PrizeSection />
        <StatsSection />
        <SdkSection />
        <TeamSection />
        <RoadmapSection />
        <PartnersSection />
        <StaySection />
      </Main>
      <Footer />
    </>
  )
}
